insert into champion values ('갈리오', '비켜라', 1);
insert into champion values ('갱플랭크', '불의심판', 1);
insert into champion values ('나서스', '꽁', 1);
insert into champion values ('누누', '데굴데굴로봇궁', 5);
insert into champion values ('닐라', '환희', 3);
insert into champion values ('드레이븐', '죽음의소용돌이', 2);
insert into champion values ('람머스', '모래폭격', 3);
insert into champion values ('럭스', '광휘의특이점', 1);
insert into champion values ('레넥톤', '강신', 1);
insert into champion values ('레오나', '최후의보루', 5);
insert into champion values ('렐', '강철의결속', 2);
insert into champion values ('룰루', '반짝반짝창', 1);
insert into champion values ('르블랑', '악의의인장', 3);
insert into champion values ('리신', '방호', 2);
insert into champion values ('리븐', '토끼검술', 3);
insert into champion values ('말파이트', '지면강타', 2);
insert into champion values ('모데카이저', '스카이라인', 5);
insert into champion values ('미스포츈', '쌍권총난사', 4);
insert into champion values ('바이', '폭발보호막', 2);
insert into champion values ('베인', '은화살', 3);
insert into champion values ('벨베스', '끝없는연희', 4);
insert into champion values ('벨코즈', '얼어붙은무덤', 3);
insert into champion values ('블리츠크랭크', '정전기방어체계', 1);
insert into champion values ('비에고', '심장파괴자', 4);
insert into champion values ('뽀삐', '방패던지기', 1);
insert into champion values ('사미라', '천부적재능', 4);
insert into champion values ('사일러스', '전투폭발', 1);
insert into champion values ('세나', '꿰뚫는어둠', 3);
insert into champion values ('세주아니', '빙겱탄', 4);
insert into champion values ('세트', '메카강타', 4);
insert into champion values ('소나', '연쇄크레센도', 3);
insert into champion values ('소라카', '별부름', 4);
insert into champion values ('시비르', '피자배달', 2);
insert into champion values ('신드라', '의지의힘', 5);
insert into champion values ('아우렐리온솔', '유성우', 4);
insert into champion values ('아펠리오스', '신념의무기', 5);
insert into champion values ('알리스타', '분쇄', 3);
insert into champion values ('애니', '폭발보호막', 2);
insert into champion values ('애쉬', '궁사의집중', 1);
insert into champion values ('야스오', '강철폭풍', 2);
insert into champion values ('에코', '별의도약', 4);
insert into champion values ('오공', '바위피부', 1);
insert into champion values ('우르곳', '역류', 5);
insert into champion values ('유미', '사르르탄', 2);
insert into champion values ('이즈리얼', '방해공작', 2);
insert into champion values ('자크', '공생적분열', 4);
insert into champion values ('잔나', '회오리바람', 5);
insert into champion values ('잭스', '적응형타격', 3);
insert into champion values ('제드', '강화살상모드', 4);
insert into champion values ('조이', '헤롱헤롱쿨쿨방울', 3);
insert into champion values ('징크스', '생선대가리', 2);
insert into champion values ('초가스', '우주의울음소리', 3);
insert into champion values ('카밀', '전술적휩쓸기', 2);
insert into champion values ('카이사', '별빛충전', 3);
insert into champion values ('케일', '화염주문검', 1);
insert into champion values ('탈론', '황소부대식외교', 1);
insert into champion values ('탈리야', '바위술사의벽', 4);
insert into champion values ('피들스틱', '어둠의수확', 5);
insert into champion values ('피오라', '준비태세', 2);

create table champion(
    name nvarchar2(10) primary key,
    skill nvarchar2(15)  not null,
    price number(4)
);

create table synerge(
    name nvarchar2(7) primary key,
    synerge1 nvarchar2(15),
    synerge2 nvarchar2(15),
    synerge3 nvarchar2(15)
);
insert into synerge values ('갈리오', '민간인', '마스코트', null);
insert into synerge values ('갱플랭크', '우세', '결투가', null);
insert into synerge values ('나서스', '동물특공대', '마스코트', null);
insert into synerge values ('누누', '기계유망주', '마스코트', null);
insert into synerge values ('닐라', '별수호자', '결투가', null);
insert into synerge values ('드레이븐', '메카프라임', '에이스', null);
insert into synerge values ('람머스', '위협', null, null);
insert into synerge values ('럭스', '별 수호자', '주문투척자', null);
insert into synerge values ('레넥톤', '레이저단', '싸움꾼', null);
insert into synerge values ('레오나', '메카프라임', '무법자', '방패대');
insert into synerge values ('렐', '별 수호자', '엄호대', null);
insert into synerge values ('룰루', '기계유망주', '선의', null);
insert into synerge values ('르블랑', '자동방어체계', '주문투척자', '해커');
insert into synerge values ('리신', '우세', '선의', '싸움꾼');
insert into synerge values ('리븐', '동물특공대', '싸움꾼', '엄호대');
insert into synerge values ('말파이트', '우세', '마스코트', null);
insert into synerge values ('모데카이저', '레이저단', '에이스', null);
insert into synerge values ('미스포츈', '동물특공대', '에이스', null);
insert into synerge values ('바이', '지하세계', '방패대', '싸움꾼');
insert into synerge values ('베인', '동물특공대', '결투가', '정찰단');
insert into synerge values('벨베스', '위협', null, null);
insert into synerge values('벨코즈',  '위협', null, null);
insert into synerge values('블리츠크랭크', '자동방어체계', '싸움꾼', null);
insert into synerge values('비에고' ,'황소부대', '무법자', null);
insert into synerge values('뽀삐' ,'기계유망주', '엄호대', null);
insert into synerge values('사미라' ,'지하세계', '에이스', '특등사수');
insert into synerge values('사일러스' ,'동물특공대' ,'무법자', null);
insert into synerge values('세나' ,'레이저단', '특등사수', null);
insert into synerge values('세주아니' ,'레이저단', '싸움꾼', null);
insert into synerge values('세트' ,'메카:프라임' ,'엄호대', null);
insert into synerge values('소나' ,'지하세계', '선의', ' 주문투척자');
insert into synerge values('소라카' ,'자동방어체계', '선의', null);
insert into synerge values('시비르' ,'민간인', '특등사수', null);
insert into synerge values('신드라' ,' 별 수호자', '선의', null);
insert into synerge values('아우렐리온솔' ,'위협', null, null);
insert into synerge values('아펠리오스' ,'병기고', '황소부대', '특등사수');
insert into synerge values('알리스타' ,' 황소부대', '마스코트', '방패대');
insert into synerge values('애니' ,'기계유망주', '황소부대', '주문투척자');
insert into synerge values('애쉬' ,'레이저단', '정찰단', null);
insert into synerge values('야스오','레이저단', '결투가', null);
insert into synerge values('에코', '별수호자', '방패대', '익살꾼');
insert into synerge values('오공', '메카프라임', '엄호대', null);
insert into synerge values('우르곳', '위협', null, null);
insert into synerge values('유미', '별수호자', '마스코트', '선의');
insert into synerge values('이즈리얼', '지하세계', '정찰단', null);
insert into synerge values('자크', '위협', null, null);
insert into synerge values('잔나', '민간인', '기상캐스터', '주문투척자');
insert into synerge values('잭스', '메카프라임', '싸움꾼', null);
insert into synerge values('제드', '레이저단', '결투가', '해커');
insert into synerge values('조이', '기계유망주', '익살꾼', '해커');
insert into synerge values('징크스', '동물특공대', '익살꾼', null);
insert into synerge values('초가스', '위협', null, null);
insert into synerge values('카밀', '자동방어체계', '무법자', null);
insert into synerge values('카이사', '별수호자', '정찰단', null);
insert into synerge values('케일', '지하세계', '결투가', null);
insert into synerge values('탈론', '황소부대', '무법자', null);
insert into synerge values('탈리야', '별수호자', '주문투척자', null);
insert into synerge values('피들스틱', '위협', '타락', null);
insert into synerge values('피오라', '황소부대', '결투가', null);
commit;

select * from champion;
select * from synerge;